### ISSUE TITLE
Bug crash app when call below build(BuildContext context)

### ISSUE THREAD

**Issue by jackyhieu1211-hn** [fayaz07/progress_dialog#27]
Hello admin. 

I use lib:

```
class UpdateAccountState extends State<UpdateAccount>{
ProgressDialog _progressDialog;
  @override
  Widget build(BuildContext context) {
    _progressDialog = ProgressDialog(context);
    _getUserInfo();
}

_getUserInfo() async {
  _progressDialog?.show();
 var userRe = await userRepo.find();
 if (_progressDialog.isShowing()) _progressDialog.hide();
}
}

```
App show error below. 

```
**E/flutter (20452): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() or markNeedsBuild() called during build.
E/flutter (20452): This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (20452): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (20452):   Overlay-[LabeledGlobalKey<OverlayState>#b9d5c]
E/flutter (20452): The widget which was currently being built when the offending call was made was:
E/flutter (20452):   UpdateAccount
E/flutter (20452): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3704:11)
E/flutter (20452): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3719:6)
E/flutter (20452): #2      State.setState (package:flutter/src/widgets/framework.dart:1161:14)
E/flutter (20452): #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:346:5)
E/flutter (20452): #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:43:24)
E/flutter (20452): #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:180:11)
E/flutter (20452): #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:923:11)
E/flutter (20452): #7      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1789:11)
E/flutter (20452): #8      showGeneralDialog (package:flutter/src/widgets/routes.dart:1582:53)
E/flutter (20452): #9      showDialog (package:flutter/src/material/dialog.dart:697:10)
E/flutter (20452): #10     ProgressDialog.show (package:progress_dialog/progress_dialog.dart:129:7)
E/flutter (20452): #11     UpdateAccountState._getUserInfo (package:htsv/screen/account.dart:37:22)
E/flutter (20452): <asynchronous suspension>
E/flutter (20452): #12     UpdateAccountState.build (package:htsv/screen/account.dart:60:5)
E/flutter (20452): #13     StatefulElement.build (package:flutter/src/widgets/framework.dart:4064:27)
E/flutter (20452): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3958:15)
E/flutter (20452): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
E/flutter (20452): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
E/flutter (20452): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)
E/flutter (20452): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
E/flutter (20452): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (20452): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (20452): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
E/flutter (20452): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (20452): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (20452): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
E/flutter (20452): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
E/flutter (20452): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
E/flutter (20452): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
E/flutter (20452): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (20452): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (20452): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
E/flutter (20452): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (20452): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (20452): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
E/flutter (20452): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (20452): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (20452): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
E/flutter (20452): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
E/flutter (20452): #38     ComponentElement._firstBuild (package:flutter/src/wi

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#15264](dirty, state: _OverlayEntryState#12763):
The method 'drive' was called on null.
Receiver: null
Tried calling: drive<Color>(Instance of '_ChainedEvaluation<Color>')

User-created ancestor of the error-causing widget was: 
  MaterialApp file:///main.dart:18:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ModalRoute._buildModalBarrier (package:flutter/src/widgets/routes.dart:1243:48)
#2      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4064:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3958:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/animation/animations.dart': Failed assertion: line 376 pos 15: 'parent != null': is not true.
User-created ancestor of the error-causing widget was: 
  MaterialApp file:main.dart:18:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
The method 'drive' was called on null.
Receiver: null
Tried calling: drive<Color>(Instance of '_ChainedEvaluation<Color>')*

```

**Comment by fayaz07** [comment]
Study the rules of build method, build method will execute infinite no. of times, you cannot call, you cannot perform that action infinite number of times and it's not bug in the package, it's fault in your code

**Comment by fayaz07** [comment]
If you really need to execute something, when the screen is shown up, you need to use **initState()** or write the code below in **build()** method, this will execute only for once after the widget is attatched to tree
```dart
WidgetsBinding.instance.addPostFrameCallback((Duration d) {
        // your code here
      });
```
