### ISSUE TITLE
Error: type 'FlutterError' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by rignaneseleo** [fayaz07/progress_dialog#57]
Hi, I'm getting this error on v1.2.2:

```
E/flutter (16962): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type 'FlutterError' is not a subtype of type 'String'
E/flutter (16962): #0      ProgressDialog.hide (package:progress_dialog/progress_dialog.dart:119:18)
E/flutter (16962): #1      restoreDataFromFile (package:my_grand_kids/managers/backups_manager.dart:427:33)
```

This is what I have on backups_manager.dart:427:
`if (context != null) await pr.hide();`
where `pr` is a `ProgressDialog`.

What could that be?

**Comment by haaris94** [comment]
I am also getting the above error
